name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code on server
        run: |
          cd /home/ival/apps/portfolio
          git fetch origin
          git reset --hard origin/main

      - name: Stop old container
        run: |
          cd /home/ival/apps/portfolio
          docker compose down || true

      - name: Build and start container
        run: |
          cd /home/ival/apps/portfolio
          docker compose up -d --build

      - name: Clean unused docker resources (optional)
        run: |
          docker system prune -f
